type Props = {
  params: { id: string };
};

export default function TestsPage({ params: { id } }: Props) {
  return (
    <div className="flex flex-col gap-3">
      <h1 className="text-2xl font-bold">Test {id}</h1>
      <p>
        This is a reading comprehension test generated by Large Language Model.
        Please read the passage and answer the questions.
      </p>
    </div>
  );
}
